export const SITE = 'https://polyakovin.github.io/game-dev-db';
export const REPO = 'https://github.com/polyakovin/game-dev-db';
export const BASE = '/game-dev-db';
export const locales = ['ru', 'en'] as const;
export type Locale = (typeof locales)[number];
export const categories = [
  'foundations',
  'design',
  'engineering',
  'workflow',
] as const;
export const path = (relative = '') => `${BASE}/${relative.replace(/^\//, '')}`;
export const absolute = (relative = '') =>
  `${SITE}/${relative.replace(/^\//, '')}`;
export const ui = {
  ru: {
    catalog: 'База знаний',
    resources: 'Ресурсы',
    mechanics: 'Механики',
    agents: 'Для ИИ-агентов',
    contribute: 'Дополнить базу',
    navigation: 'Навигация',
    categories: 'Направления',
    open: 'Открытый проект',
    tagline: 'Делаем игры осознанно.',
    skip: 'Перейти к содержимому',
    foundations: 'Основы',
    design: 'Геймдизайн',
    engineering: 'Разработка',
    workflow: 'Рабочий процесс',
    all: 'Все темы',
    beginner: 'Базовый',
    intermediate: 'Средний',
    minutes: 'мин',
    search: 'Найти принцип, тему или инструмент…',
    searchLabel: 'Поиск по базе знаний',
    lessons: 'Материалы',
    results: 'Найдено',
    empty: 'Пока ничего не нашлось',
    emptyHelp: 'Попробуйте другой запрос или выберите все темы.',
    reset: 'Сбросить поиск',
    toc: 'В этом материале',
    sources: 'Источники и дальнейшее чтение',
    updated: 'Обновлено',
    edit: 'Предложить правку',
    markdown: 'Читать Markdown',
    back: 'Все материалы',
    footer: 'Создаётся сообществом для людей и агентов.',
    license: 'Код MIT · Материалы CC BY 4.0',
  },
  en: {
    catalog: 'Knowledge base',
    resources: 'Resources',
    mechanics: 'Mechanics',
    agents: 'For AI agents',
    contribute: 'Contribute',
    navigation: 'Navigation',
    categories: 'Explore by topic',
    open: 'Open-source project',
    tagline: 'Make games with intent.',
    skip: 'Skip to content',
    foundations: 'Foundations',
    design: 'Game design',
    engineering: 'Engineering',
    workflow: 'Workflow',
    all: 'All topics',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    minutes: 'min',
    search: 'Find a principle, topic or tool…',
    searchLabel: 'Search the knowledge base',
    lessons: 'Lessons',
    results: 'Results',
    empty: 'No matching lessons yet',
    emptyHelp: 'Try a different query or explore all topics.',
    reset: 'Reset search',
    toc: 'On this page',
    sources: 'Sources and further reading',
    updated: 'Updated',
    edit: 'Suggest an edit',
    markdown: 'Read Markdown',
    back: 'All lessons',
    footer: 'Built by the community for people and agents.',
    license: 'Code MIT · Content CC BY 4.0',
  },
} as const;

export const order = [
  'scope-and-prototype',
  'game-loop',
  'state-machines',
  'input-and-feedback',
  'collision-basics',
  'game-feel',
  'performance-budget',
  'agent-workflow',
];
